"""add_earth_bookmarks

Revision ID: 4377579d2c0a
Revises: a46b24721444
Create Date: 2026-07-21 20:08:32.599970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4377579d2c0a'
down_revision: Union[str, Sequence[str], None] = 'a46b24721444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earth_bookmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commander_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['commanders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earth_bookmarks_commander_id'), 'earth_bookmarks', ['commander_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earth_bookmarks_commander_id'), table_name='earth_bookmarks')
    op.drop_table('earth_bookmarks')
    # ### end Alembic commands ###
