"""add_search_history

Revision ID: 4f8f9a0287b9
Revises: e6423891da6b
Create Date: 2026-07-23 20:16:57.152562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8f9a0287b9'
down_revision: Union[str, Sequence[str], None] = 'e6423891da6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commander_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['commanders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commander_id', 'item_id', 'item_type', name='uq_pinned_result')
    )
    op.create_index(op.f('ix_pinned_results_commander_id'), 'pinned_results', ['commander_id'], unique=False)
    op.create_index(op.f('ix_pinned_results_item_id'), 'pinned_results', ['item_id'], unique=False)
    op.create_index(op.f('ix_pinned_results_item_type'), 'pinned_results', ['item_type'], unique=False)
    op.create_table('recent_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commander_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('normalized_query', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['commanders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_searches_commander_id'), 'recent_searches', ['commander_id'], unique=False)
    op.create_index(op.f('ix_recent_searches_normalized_query'), 'recent_searches', ['normalized_query'], unique=False)
    op.create_index(op.f('ix_recent_searches_timestamp'), 'recent_searches', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recent_searches_timestamp'), table_name='recent_searches')
    op.drop_index(op.f('ix_recent_searches_normalized_query'), table_name='recent_searches')
    op.drop_index(op.f('ix_recent_searches_commander_id'), table_name='recent_searches')
    op.drop_table('recent_searches')
    op.drop_index(op.f('ix_pinned_results_item_type'), table_name='pinned_results')
    op.drop_index(op.f('ix_pinned_results_item_id'), table_name='pinned_results')
    op.drop_index(op.f('ix_pinned_results_commander_id'), table_name='pinned_results')
    op.drop_table('pinned_results')
    # ### end Alembic commands ###
