"""add_theme_overrides

Revision ID: 863a1731e2ac
Revises: 4f8f9a0287b9
Create Date: 2026-07-24 20:16:35.010723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863a1731e2ac'
down_revision: Union[str, Sequence[str], None] = '4f8f9a0287b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('accent_color', sa.String(length=30), nullable=True))
    op.add_column('settings', sa.Column('panel_opacity', sa.Float(), nullable=False, server_default='0.85'))
    op.add_column('settings', sa.Column('glow_intensity', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('settings', sa.Column('animation_speed', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('settings', sa.Column('border_radius', sa.String(length=20), nullable=False, server_default='4px'))
    op.add_column('settings', sa.Column('font_size', sa.String(length=20), nullable=False, server_default='14px'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'font_size')
    op.drop_column('settings', 'border_radius')
    op.drop_column('settings', 'animation_speed')
    op.drop_column('settings', 'glow_intensity')
    op.drop_column('settings', 'panel_opacity')
    op.drop_column('settings', 'accent_color')
    # ### end Alembic commands ###
